version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3002:3002"
    links:
      - mongodb:27017
  mongodb:
    container_name: mongo
    image: mongo:latest
    expose:
      - 27017
    ports:
      - "27017:27017"
